name: Security Scan

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  security-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t security_cicd:beta .
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: 'security_cicd:beta'
          vuln-type: 'os,library'
          format: 'table'

      - name: Install Semgrep
        run: |
          sudo pip install semgrep --ignore-installed rich
      - name: Run Semgrep SAST
        run: |
          semgrep --config p/security-audit --error --json .

      - name: Start Docker container with application
        run: |
          docker network create zap-net
          docker run -d --name security_app --network zap-net -p 8080:8080 security_cicd:beta

      - name: Start OWASP ZAP scan
        run: |
          docker run --rm --network zap-net -v $(pwd):/zap/wrk:rw -t zaproxy/zap-stable zap-baseline.py \
            -t http://127.0.0.1:8080 \
            -r zap_report.html \

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests
        run: mvn test -B