name: Security Scan

on:
  push:
    branches:
      - 'main'

jobs:
  security-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t security_cicd:latest .
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: 'security_cicd:latest'
          vuln-type: 'os,library'
          format: 'table'

      - name: Install Semgrep
        run: |
          sudo pip install semgrep --ignore-installed rich
      - name: Run Semgrep SAST
        run: |
          semgrep --config p/security-audit --error --json .

      # OWASP ZAP
      - name: Pull OWASP ZAP Docker image
        run: |
          docker pull owasp/zap2docker-stable
      - name: Start Docker container with application
        run: |
          docker run -d --name security_app -p 8080:8080 security_cicd:latest
      - name: Start OWASP ZAP scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk:rw -t owasp/zap2docker-stable zap-baseline.py \
            -t http://localhost:8080 \
            -r zap_report.html \
            -d
      - name: Upload OWASP ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: SecurityReports/zap_report.html

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests
        run: mvn test -B